version: '3'

services:
  insta_db:
    image: postgres:latest
    container_name: insta_db
    environment:
      - POSTGRES_USER=POSTGRES
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_DB=POSTGRES
    ports:
      - "5000:5432"
    volumes:
      - insta_db_vol:/var/lib/postgresql/data

volumes:
  insta_db_vol:
    external: true


