# Generated by Django 4.1.7 on 2023-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedproject',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptedproject',
            name='is_delete_project',
            field=models.BooleanField(default=False),
        ),
    ]
