# Generated by Django 4.1.7 on 2023-04-04 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='projects/files'), blank=True, null=True, size=None),
        ),
    ]
