# Generated by Django 4.1.7 on 2023-04-05 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0002_alter_project_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
