# Generated by Django 4.1.7 on 2023-04-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_acceptedproject_is_cancel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedproject',
            name='is_cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acceptedproject',
            name='is_delete_project_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
