# Generated by Django 4.1.7 on 2023-04-05 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_admin_user'),
        ('Project', '0003_alter_project_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.admin'),
        ),
    ]
