# Generated by Django 4.1.7 on 2023-04-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_acceptedproject_is_cancel_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedproject',
            name='is_delete_project',
        ),
        migrations.RemoveField(
            model_name='acceptedproject',
            name='is_delete_project_at',
        ),
    ]
