# Generated by Django 4.1.7 on 2023-04-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_alter_project_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
