# Generated by Django 4.1.7 on 2023-04-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_remove_acceptedproject_is_delete_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedproject',
            name='is_delete_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptedproject',
            name='is_delete_project_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
