# Generated by Django 4.1.7 on 2023-04-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_project_delete_at_project_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='delete_at',
            new_name='deleted_at',
        ),
    ]
