# Generated by Django 4.1.7 on 2023-04-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_rename_delete_at_project_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='publish',
            new_name='is_publish',
        ),
    ]
