# Generated by Django 4.1.7 on 2023-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_rename_publish_project_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
