# Generated by Django 4.1.7 on 2023-04-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_project_reject_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedproject',
            old_name='pending',
            new_name='is_accepted',
        ),
    ]
