# Generated by Django 4.1.7 on 2023-04-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_rename_pending_acceptedproject_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedproject',
            name='accept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
