# Generated by Django 4.1.7 on 2023-04-07 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_alter_acceptedproject_accept_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedproject',
            old_name='is_accepted',
            new_name='pending',
        ),
    ]
