# Generated by Django 4.1.7 on 2023-04-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0006_alter_freelancer_verified_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1028)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.account')),
            ],
        ),
    ]
