# Generated by Django 4.1.7 on 2023-04-09 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Answered', 'Answered'), ('Pending', 'Pending'), ('Closed', 'Closed')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2048)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ticket.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='AdminAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.admin')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ticket.conversation')),
            ],
        ),
    ]
