# Generated by Django 4.1.7 on 2023-04-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='title',
            new_name='subject',
        ),
    ]
