# Generated by Django 4.1.7 on 2023-04-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '__first__'),
        ('Ticket', '0003_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_awnsered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='responsive_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.admin'),
        ),
    ]
