# Generated by Django 4.1.7 on 2023-04-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
