# Generated by Django 4.1.7 on 2023-04-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_freelancer_reject_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Account.instagramaccount'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rule',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
