# Generated by Django 4.1.7 on 2023-04-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_freelancer_instagram_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='instagram_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Account.instagramaccount'),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
