# Generated by Django 4.1.7 on 2023-04-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_freelancer_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
