# Generated by Django 4.1.7 on 2023-04-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_rule', models.CharField(choices=[('superuser', 'superuser'), ('admin', 'admin'), ('unknown', 'unknown')], max_length=15)),
            ],
        ),
    ]
