# Generated by Django 4.1.7 on 2023-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial', '0002_alter_withdraw_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='cancel_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
